export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const NATIONALITY_TO_CODE: Record<string, string> = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Angola: "AO",
  Argentina: "AR",
  Armenia: "AM",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Belgium: "BE",
  "Bosnia-Herzegovina": "BA",
  Bosnia: "BA",
  Brazil: "BR",
  Bulgaria: "BG",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  Congo: "CG",
  "Costa Rica": "CR",
  Croatia: "HR",
  "Czech Republic": "CZ",
  Czechia: "CZ",
  Denmark: "DK",
  Ecuador: "EC",
  Egypt: "EG",
  England: "GB-ENG",
  Estonia: "EE",
  Ethiopia: "ET",
  Finland: "FI",
  France: "FR",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Honduras: "HN",
  Hungary: "HU",
  Iceland: "IS",
  Iran: "IR",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  "Ivory Coast": "CI",
  Jamaica: "JM",
  Japan: "JP",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kosovo: "XK",
  Latvia: "LV",
  Lithuania: "LT",
  Luxembourg: "LU",
  Mali: "ML",
  Malta: "MT",
  Mexico: "MX",
  Moldova: "MD",
  Montenegro: "ME",
  Morocco: "MA",
  Mozambique: "MZ",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nigeria: "NG",
  "North Macedonia": "MK",
  "Northern Ireland": "GB",
  Norway: "NO",
  Panama: "PA",
  Paraguay: "PY",
  Peru: "PE",
  Poland: "PL",
  Portugal: "PT",
  Romania: "RO",
  Russia: "RU",
  Scotland: "GB-SCT",
  Senegal: "SN",
  Serbia: "RS",
  Slovakia: "SK",
  Slovenia: "SI",
  Somalia: "SO",
  "South Korea": "KR",
  Spain: "ES",
  Sudan: "SD",
  Sweden: "SE",
  Switzerland: "CH",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Togo: "TG",
  Tunisia: "TN",
  Turkey: "TR",
  Ukraine: "UA",
  Uruguay: "UY",
  USA: "US",
  "United States": "US",
  Venezuela: "VE",
  Wales: "GB-WLS",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};

export function nationalityFlag(nationality: string | null): string {
  if (!nationality) return "";
  const code = NATIONALITY_TO_CODE[nationality];
  if (!code) return "";
  if (code.startsWith("GB-")) return "🇬🇧";
  return code
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(0x1f1e6 - 65 + c.charCodeAt(0)))
    .join("");
}
